# -*- coding: utf-8 -*-
"""colatc

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPnFEBg2h6Kxf69oHt1zIiz8bU60Qz84
"""



count =0
count_max=0
#a = int(input())
import time
start=time.perf_counter()
for a in range(2,17):
  a=i
  while a!=1:
    if a%2==0:
       a=a/2
    else: 
       a = a*3+1
    count+=1
    if count > count_max:
       a_max=a
       count_max=i
all_time = time.perf_counter()-start
print(count_max)
print(a_max)
print(all_time)

