# -*- coding: utf-8 -*-
"""банкоматT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EXaJchBLgW7UtQuEqgNA5xcfCw-bVfQ
"""

print('BANK MMM')  
bancomat_atm = {
    5:20,
    10:20,
    20:30,
    50:10,
    100:10
}
zp = 1000
 
def balance():
    balance_atm=0
    balance_atm = sum([key * val for key, val in bancomat_atm.items()])
    return balance_atm
 
balance()
 
 
def pin_code():
    attempts =  0 
    while attempts < 3: #не более  3 попыток 
        #atm_pin = input('Пожалуйста введите  PIN: ') #ползовател вводит пин
        print('##############################################################')
        print('#                 Вэлкам МММ                                 #')
        print('#                                                            #')
        print('#                                                            #')
        print('#              Пожалуйста введите пин-код                    #')
        atm_pin =input('               ')
        print('#                                                            #')
        print('#                                                            #')
        print('##############################################################')
        if atm_pin == '1234': 
            #print(f'Ваш баланс:{zp}  ')
            print('##############################################################')
            print('#                        МММ                                 #')
            print('#                                                            #')
            print('#                                                            #')
            print('#                                                            #')
            print(                f'Ваш баланс:          {zp}                    ')
            print('#                                                            #')
            print('#                                                            #')
            print('##############################################################')
            break  
        elif attempts <= 1 and attempts <= 3:
            attempts += 1
            #print(f'Неправильный пин. Попробуйте снова. У Вас осталось {3 - attempts} попыт(ки/ка) ')
            error()
        else: 
            print("Карта заблокирована.")
            break
pin_code()
 
def error():
  
    print('##############################################################')
    print('#                           MMM                              #')
    print('#                                                            #')
    print('#                                                            #')
    print('#           Ошибка! Введите пин-код снова  !                 #')
    print('#                                                            #')
    print('#                                                            #')
    print('#                                                            #')
    print('##############################################################')
 
    
    pin_code()
 
    return
 
def cash():
    bancomat_atm = {
        5:20,
        10:20,
        20:10,
        50:10,
        100:10
    }
    ostatok_cash={}
    print('##############################################################')
    print('#                           MMM                              #')
    print('#                                                            #')
    print('#                                                            #')
    print('#            ВВедите сумму:                                  #')
    nal_=int(input( ))
    print('#                                                            #')
    print('#                                                            #')
    print('#                                                            #')
    print('##############################################################')
    #nal_=int(input('Введите сумму: '))
    if nal_ > zp :
       #print('Недостаточно средств: ')
        print('##############################################################')
        print('#                           MMM                              #')
        print('#                                                            #')
        print('#                                                            #')
        print('#             Недостаточно средств                           #')
        print('#                                                            #')
        print('#                                                            #')
        print('#                                                            #')
        print('##############################################################')
        print('##############################################################')
        print('#                           MMM                              #')
        print('#                                                            #')
        print('#                                                            #')
        print('#            ВВедите сумму:                                  #')
        nal_=int(input( ))
        print('#                                                            #')
        print('#                                                            #')
        print('#                                                            #')
        print('##############################################################')
       #nal_=int(input('Введите сумму: '))
    hundred= int(nal_//100)
    fifty =0
    twenty = 0
    ten = int (((nal_ - hundred*100))//10)
 
    if nal_%100 > 50:
        fifty = 1
    if nal_ < 100:
      twenty = nal_//20
      fifty=0
    if nal_>100 and ten>5:
      ten = ten - 5
    else:
        ten = 1
      
    if nal_%10 == 5:
        five = 1
        cash_user_={
        5:1,
        10:ten,
        20:twenty,
        50:fifty,
        100:hundred
        }
    else:
        cash_user_={
        10:ten,
        50:fifty,
        20:twenty,
        100:hundred
        }
    for k, v in bancomat_atm.items():
        ostatok_cash[k] = v - cash_user_.get(k, 0)
    return ostatok_cash
 
cash()