# -*- coding: utf-8 -*-
"""Обои

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M9fWa5rc7KjgQQxAUx03worriKG7KLRR
"""

class WinDoor:
     def __init__(self, x, y, name="unk"):
       self.x = x
       self.y = y
       self.name = name
       self.square = x * y 
 
     def __repr__(self):
       return f'{self.name} {self.x}x{self.y}'
 
 
class Room:
 
    def __init__(self, x, y, z):
        self.square = 2 * z * (x + y)
        self.wd = []
        self.x = x
        self.y = y 
        self.z = z
 
    def addWD(self, w, h, name='unk'):
        self.wd.append(WinDoor(w, h, name))
        
    def workSurface(self):
        new_square = self.square
        for i in self.wd:
            new_square -= i.square
        return new_square
    def rulon(self,l,w):
        quantity = round(self.workSurface()/(l*w))
        if self.workSurface()%(l*w) < 5:
            quantity +=1
        return quantity
 
 
x = float(input('Будьте добры указать длину комнаты: '))
y = float(input('Будьте добры указать ширину комнаты: '))
z = float(input('Будьте добры указать высоту комнаты: '))
n = int(input('Введите общее количество окон и дверей в комнате: '))
 
a = Room(x,y,z)
 
print('Далее, добавьте высоту и ширину оконных проемов и дверей.')
count = 0
while count < n:
    count += 1
    w = float(input('Введите ширину проема: '))
    h = float(input('Введите высоту проема: '))
    a.addWD(w,h)
 
print('Далее, будьте готовы ввести параметры руллонов, понравившихся Вам обоев(длина,ширина трубки).')
 
l = float(input('Введите длину трубки: '))
w = float(input('Введите ширину трубки: '))
 
print(f"Площадь поверхности для оклейки составляет: {a.workSurface()} кв.м.")
print(f"Всего нужно {a.rulon(l, w)} рулона(ов).")