# -*- coding: utf-8 -*-
"""скобки.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_saa0P6XagTTFEp8FC-x-JFnISRNbtwX
"""

def check(my_string):

    brackets = ['()', '{}', '[]']

    while any(x in my_string for x in brackets):

        for br in brackets:

            my_string = my_string.replace(br, '')

    return not my_string

   

string = "{[]{()}}"

print(string, "-", "Balanced" if check(string) else "Unbalanced")